### ISSUE TITLE
Running into some issues while using Windows system calls

### ISSUE THREAD

**Issue by 870045787** [WonderLandxD/opensdpc#17]
Thanks for your efforts, I'm having some issues with windows system calls. My python version is 3.9, and here's the error message
Traceback (most recent call last):
  File "F:\Pythoncode\learn_pytorch\asd.py", line 6, in <module>
    import opensdpc
  File "D:\anaconda\ascii\envs\pytorch\lib\site-packages\opensdpc\__init__.py", line 1, in <module>
    from opensdpc.OpenSdpc import OpenSdpc
  File "D:\anaconda\ascii\envs\pytorch\lib\site-packages\opensdpc\OpenSdpc.py", line 25, in <module>
    os.chdir(os.path.join(dirname, 'WINDOWS\\dll'))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\anaconda\\ascii\\envs\\pytorch\\lib\\site-packages\\opensdpc\\WINDOWS\\dll'

**Comment by KennyKwokProg** [comment]
I have settled the error by following steps.

1. Copy the dll from "xxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\sdpc\DLL\dll"
2. Create folder "WINDOWS" and subfolder "dll" on following directory "xxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\opensdpc\"
3. Paste the dll copied in step 1 to the folder dll created in step 2.

Please try.
